#! /bin/sh
sxhkd &
lxsession &

bspc monitor -d 1 2 3 4 5 6 7 8
bspc rule -r "*"
bspc config border_width         6
bspc config single_monocle	true
bspc config window_gap         	 0 
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer 	true
bspc config focused_border_color "#4d6d79"
bspc config normal_border_color "#1e2b30"
bspc config presel_feedback_color "#4d6d79"

bspc rule -a Xarchiver state=floating
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a canto desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Signal desktop='^7' 
bspc rule -a ranger desktop='^3'
bspc rule -a Steam desktop='^7' state=floating
bspc rule -a transmission desktop='^5'
bspc rule -a qBittorrent desktop='^5'
bspc rule -a Virt-manager desktop='^4'
bspc rule -a Galculator state=floating
bspc rule -a GParted state=floating
bspc rule -a Xscreensaver-demo state=floating
bspc rule -a Font-manager state=floating
bspc rule -a Vlc desktop='^3' follow=on focus=on
bspc rule -a Thunar state=floating
bspc rule -a jetbrains-idea-ce desktop='^1'
bspc rule -a "Apache NetBeans IDE 11.3" desktop='^1'
bspc rule -a Font-viewer state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Yad state=floating
bspc rule -a Lutris desktop='^6'
bspc rule -a Wine desktop='^6'
bspc rule -a "TeamSpeak 3" desktop='^7'

# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr

# Set backgroud
feh --bg-fill ~/Pictures/bg.png

# Launch polybar
~/.config/polybar/launch.sh
xdo activate -N firefox || firefox


pkill dunst &
# Autostart
picom &
dunst &


#Notifications
pid_picom=$(pidof picom)
pid_sxhkd=$(pidof sxhkd)
 
if [ "$pid_picom" ]; then
	notify-send "picom has been (re)started."
else
	notify-send "picom failed to start." -u critical
fi
 
if [ "$pid_sxhkd" ]; then
	notify-send "sxhkd has been (re)started."
else
	notify-send "sxhkd failed to start." -u critical
fi
notify-send "bspwm has been (re)started."


